nelmio_api_doc:
    documentation:
        info:
            title: API Étudiants
            description: API REST de gestion d'un annuaire d'étudiants
            version: 1.0.0
    areas:
        path_patterns:
            - ^/v1
